### Create Detail User
POST http://localhost:4000/v1/api/attendance/In
Content-Type: application/json
X-timestamp: 1747563838
X-Signature: 26eee162621ba3b78aff395780cffd29d84d19b562a4ab86a52ad286b620022b

{
    "longitude": "-6.189035",
    "latitude": "106.640455"
}

### Create Detail User
POST http://localhost:4000/v1/api/attendance/Out
Content-Type: application/json
X-timestamp: 1747563838
X-Signature: 26eee162621ba3b78aff395780cffd29d84d19b562a4ab86a52ad286b620022b

{
    "longitude": "-6.189035",
    "latitude": "106.640455"
}

### Create Detail User
GET http://localhost:4000/v1/api/attendance/get-all
Content-Type: application/json

### Create Detail User
GET http://localhost:4000/v1/api/attendance/get-byid
Content-Type: application/json
