version: "3.8"

services:
  app:
    build: .
    ports:
      - "9228:3000"
    environment:
      - DATABASE_URL_MAIN="mysql://root:50p4y5ky0v0!@8.215.44.147:3306/absensiDB"
      - DATABASE_URL_SECONDARY="mysql://root:50p4y5ky0v0!@8.215.44.147:3306/db_skyccc"
      - NODE_ENV=production
      - JWT_SECRET=158243e2-ccc0-4798-a944-2a5b0d1c90f3
      - SIGNATURE_SECRET=c719f771-69ce-4945-9895-1759fb49df87
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  postgres_data:
